#!/bin/bash

#if ! [ -e /etc/apt/preferences.d/mozillateamppa ]; then
  echo "=Remove failer nautilus and Install nemo ="
  echo " remove Nautilus to nemo from dock as favorite"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp |  sed -e "s/org.gnome.Nautilus.desktop/nemo.desktop/g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"  
  #snap list contain firefox?
  if apt list --installed | grep nautilus/noble; then
    echo " Remove Nautilus"
#    echo "  CAUTION!!:if remove command is waited longtime,stop this script(quit at Window-close button or ^c) and run update-manager for update all snap!!"
    sudo apt remove -y --purge nautilus
    sudo apt remove -y --autoremove firefox >/dev/null 2>/dev/null
  fi
#  echo " Add nemo"
  echo " Install nemo"
  sudo apt update >/dev/null 2>/dev/null
  sudo apt -y install nemo
#  echo " Install nemo to dock as favorite"
  echo ""
  echo -n "Hit Any Key:"
  read -r -n 1 -s answer
  echo ""
#fi

