#!/bin/bash

#if ! [ -e /etc/apt/preferences.d/mozillateamppa ]; then
  echo "=Remove failer thunar ="
  echo " remove thunar from dock as favorite"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp |  sed -e "s/'thunar.desktop',//g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"  
  #snap list contain firefox?
  if apt list --installed | grep nemo/noble; then
    echo " Remove thunar"
#    echo "  CAUTION!!:if remove command is waited longtime,stop this script(quit at Window-close button or ^c) and run update-manager for update all snap!!"
    sudo apt remove -y --purge nemo "thunar*"
    sudo apt remove -y --autoremove >/dev/null 2>/dev/null
  fi
  echo ""
  echo -n "Hit Any Key:"
  read -r -n 1 -s answer
  echo ""
#fi

