#!/bin/bash

#if ! [ -e /etc/apt/preferences.d/mozillateamppa ]; then
  echo "=Remove failer nemo ="
  echo " remove nemo from dock as favorite"
  tmp=`gsettings get org.gnome.shell favorite-apps`
  tmp=`echo $tmp |  sed -e "s/'nemo.desktop',//g"`
  gsettings set org.gnome.shell favorite-apps "$tmp"  
  #snap list contain firefox?
  if apt list --installed | grep nemo/noble; then
    echo " Remove nemo"
#    echo "  CAUTION!!:if remove command is waited longtime,stop this script(quit at Window-close button or ^c) and run update-manager for update all snap!!"
    sudo apt remove -y --purge nemo nemo-audio-tab nemo-compare nemo-dropbox nemo-emblems nemo-filename-repairer nemo-fileroller nemo-image-converter nemo-media-columns nemo-pastebin nemo-preview nemo-python nemo-seahorse nemo-share nemo-terminal
    sudo apt remove -y --autoremove >/dev/null 2>/dev/null
  fi
  echo ""
  echo -n "Hit Any Key:"
  read -r -n 1 -s answer
  echo ""
#fi

