#!/bin/bash

asksure() {
  echo -n "Are you sure (Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo # just a final linefeed, optics...
  return $retval
}
removeallmoethemes() {
  echo "=Remove MoeAllColor theme="
  if [ -d /usr/share/themes/Moe-Green16 ]; then
    sudo rm -rf /usr/share/themes/Moe-Green16
  fi
  if [ -d /usr/share/themes/Moe-BlueGreen16 ]; then
    sudo rm -rf /usr/share/themes/Moe-BlueGreen16
  fi  
  if [ -d /usr/share/themes/Moe-Navy16 ]; then
    sudo rm -rf /usr/share/themes/Moe-Navy16
  fi
  if [ -d /usr/share/themes/Moe-Purple16 ]; then
    sudo rm -rf /usr/share/themes/Moe-Purple16
  fi
  if [ -d /usr/share/themes/Moe-Red16 ]; then
    sudo rm -rf /usr/share/themes/Moe-Red16
  fi
  if [ -d /usr/share/themes/Moe-Orange16 ]; then
     sudo rm -rf /usr/share/themes/Moe-Orange16
  fi
  if [ -d /usr/share/themes/Moe-Yellow16 ]; then
    sudo rm -rf /usr/share/themes/Moe-Yellow16
  fi
  if [ -d /usr/share/themes/Moe-Blue16 ]; then
    sudo rm -rf /usr/share/themes/Moe-Blue16
  fi
  if [ -d /usr/share/themes/Moe-Pink16 ]; then
    sudo rm -rf /usr/share/themes/Moe-Pink16
  fi
  echo "Done"
}

removethemealtanatives() {
echo "=Remove all Moe GDM altanetives="
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Green16/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-BlueGreen16/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Navy16/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Purple16/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Red16/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Orange16/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Yellow16/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Blue16/gnome-shell/gnome-shell-theme.gresource
  sudo update-alternatives --remove gdm-theme.gresource /usr/share/themes/Moe-Pink16/gnome-shell/gnome-shell-theme.gresource
echo "Done"
}

loginlogobak() {
echo "=Login logo change to default(if exist back up)="
if [ -e /usr/share/plymouth/ubuntu-logo.org.png ]; then
  sudo cp /usr/share/plymouth/ubuntu-logo.org.png /usr/share/plymouth/ubuntu-logo.png
echo "Done"
fi
}

### main
echo "=Set theme to defalt(Yaru)="
gsettings set org.gnome.desktop.interface gtk-theme "Yaru"
gsettings set org.gnome.shell.extensions.user-theme name "Yaru"
echo "Done"
# delete Moe-theme
echo ""
removeallmoethemes;
echo ""
# GDM theme to default
echo "=Set GDM Altanetive to Yaru(Default)="
sudo update-alternatives --set gdm-theme.gresource /usr/share/gnome-shell/theme/Yaru/gnome-shell-theme.gresource >/dev/null 2>/dev/null
echo "Done"
echo ""
removethemealtanatives;
echo ""
# login logo chane to default,if backuped
loginlogobak;
echo ""
echo -n "Hit Any Key:"
read -r -n 1 -s answer

