#!/bin/bash
#==== MoeIcon variable ====
MoeBasicWallUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/bg-basic.jpg"
MoeBasicWallFileName=`echo $MoeBasicWallUrl|awk -F"/" '{print $NF}'`
MoeWallUrl="https://github.com/mifjpn/Moebuntu-kawaiiUbuntu-ToysOriginal/raw/24.04Lts/themes/bg-default.jpg"
MoeWallFileName=`echo $MoeWallUrl|awk -F"/" '{print $NF}'`
SYSWallDir="/usr/share/backgrounds"
DefaultWallFileName="warty-final-ubuntu.png"
TempDir="Moebuntu.temp"
ConstMoeWallFileName="moe_wall.jpg"
ConstWallFileNameJpg="moe_wall.jpg"
ConstWallFileNamePng="moe_wall.png"

# Install curl
InstallCurl() {
  echo " install curl="
  dpkg -s curl >/dev/null 2>&1
  if [ ! $? -eq 0 ]; then
    sudo apt -y install curl
    else
        echo "Already Installed"
  fi
  echo ""
}

# Install imagemagick-2212291856
InstallImagemagick() {
echo " Install imagemagick"
dpkg -s imagemagick >/dev/null 2>&1
if [ ! $? -eq 0 ]; then
  sudo apt install -y imagemagick
  else
      echo " Already Installed"
fi
}

#Ask Yn
askyn() {
  echo -n "(Y/N)? "
  while read -r -n 1 -s answer; do
    if [[ $answer = [YyNn] ]]; then
      [[ $answer = [Yy] ]] && retval=0
      [[ $answer = [Nn] ]] && retval=1
      break
    fi
  done
  echo # just a final linefeed, optics...
  return $retval
}

# main
# make temp directory
if [ ! -d $TempDir ]; then
  echo " create temp folder $TempDir"
  mkdir $TempDir
fi

# install or remove?
if [ "$1" = "install" ]; then
  # install
  echo "=Install Desktop Wallpaper="
  InstallCurl;
  InstallImagemagick;
  # Ask filename of wallpaper
  read -p "Please drag-and-drop wall (png etc) image file or push only return to set example image:" FileDrop
  if [ "$FileDrop" = "" ]; then
# set default login picture
# download default login picture
    echo " You choose example image"
    echo "Apply the cute image of anime-style character drawed by Toy?"
    if ! askyn; then
      echo " Can't apply desktop wallpaper"
      # remove temp-dir
      rm -rf $TempDir
      echo ""
      echo -n "Hit Any Key:"
      read -r -n 1 -s answer
      echo ""     
      exit 0 
    fi      
    echo " download example login picture=" 
    echo " download $MoeWallFileName"
    curl -L $MoeWallUrl --output "$TempDir/$MoeWallFileName"
    echo " copy to $SYSWallDir"
    sudo cp "$TempDir/$MoeWallFileName" "$SYSWallDir/$ConstMoeWallFileName"
    echo " setting to $MoeWallFileName"
    gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$ConstMoeWallFileName"
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$ConstMoeWallFileName"
    echo "Done"
    echo " remove temp folder $TempDir"
    rm -rf $TempDir
    echo ""
    echo -n "Hit Any Key:"
    read -r -n 1 -s answer
    echo ""
    exit 0 
  else
  # FileDrop to login
    WallFileFullPath=`echo $FileDrop | tr -d \'`
    echo "=Set fileDrop $WallFileFullPath to Wallpicture="
    if [ ! -e "$WallFileFullPath" ]; then
      echo "File Not exist!"
      echo "Can not change Wallpaper"
      # remove temp-dir
      rm -rf $TempDir
      echo ""
      echo -n "Hit Any Key:"
      read -r -n 1 -s answer
      echo ""     
      exit 0   
    fi
    echo " copy $WallFileFullPath to $SYSWallDir"
    FileName=`echo $WallFileFullPath|awk -F"/" '{print $NF}'`
    FileExtension=`echo ${FileName##*.}`
    echo "Extention is $FileExtension"
    if [ $FileExtension = "jpg" ] || [ $FileExtension = "JPG" ]; then
      ConstMoeWallFileName=$ConstWallFileNameJpg
    elif [ $FileExtension = "png" ] || [ $FileExtension = "PNG" ]; then
      ConstMoeWallFileName=$ConstWallFileNamePng
    else
      echo "extention is not jpg or png."
      echo " convert to png file"
      # convert to png
      ConstMoeWallFileName=$ConstWallFileNamePng
      echo "FileExtension is $FileExtension"
      echo " Convert $WallFileFullPath to $TempDir/$ConstMoeWallFileName"
      ReturnValue=`convert "$WallFileFullPath" $TempDir/$ConstMoeWallFileName`
      if [ "$ReturnValue" != "" ]; then
        echo "Can't convert to PNG-image"
        echo "Can not change wallpaper picture"
        # remove temp-dir
        rm -rf $TempDir
        echo ""
        echo -n "Hit Any Key:"
        read -r -n 1 -s answer
        echo ""     
        exit 0
      fi
      sudo cp "$TempDir/$ConstMoeWallFileName" "$SYSWallDir/$ConstMoeWallFileName"
      echo "Done"
      echo " setting $TempDir/$ConstMoeWallFileName to $SYSWallDir/$ConstMoeWallFileName"
      gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$ConstMoeWallFileName"
      gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$ConstMoeWallFileName"
      echo "Done"
      echo " remove temp folder $TempDir"
      rm -rf $TempDir
      echo ""
      echo -n "Hit Any Key:"
      read -r -n 1 -s answer
      echo ""
      exit 0
    fi
    echo " copy $WallFileFullPath to $SYSWallDir"
    sudo cp "$WallFileFullPath" "$SYSWallDir/$ConstMoeWallFileName"
    echo " setting to $WallFileFullPath"
    gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$ConstMoeWallFileName"
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$ConstMoeWallFileName"
    echo "Done"
    echo " remove temp folder $TempDir"
     # remove temp-dir
    rm -rf $TempDir
    echo ""
    echo -n "Hit Any Key:"
    read -r -n 1 -s answer
    echo ""     
    exit 0 
  fi
  rm -rf $TempDir
  echo ""
  echo -n "Hit Any Key:"
  read -r -n 1 -s answer
  echo ""
  exit 0 
# remove
elif [ "$1" = "remove" ]; then
  echo "=Remove Moe desktop wallpaper ${MoeWallFileName%.*} and set detault="
  echo " seting to $DefaultWallFileName"
  gsettings set org.gnome.desktop.background picture-uri "file://$SYSWallDir/$DefaultWallFileName"
  gsettings set org.gnome.desktop.background picture-uri-dark "file://$SYSWallDir/$DefaultWallFileName"
  # if exsist remove MoeBuntuWall
  if [ -e "$SYSWallDir/$ConstWallFileNameJpg" ]; then
    echo " remove $SYSWallDir/$ConstWallFileNameJpg"
    sudo rm "$SYSWallDir/$ConstWallFileNameJpg"
  fi
  if [ -e "$SYSWallDir/$ConstWallFileNamePng" ]; then
    echo " remove $SYSWallDir/$ConstWallFileNamePng"
    sudo rm "$SYSWallDir/$ConstWallFileNamePng"
  fi
  echo "Done"
  echo ""
else
  echo "install? remove?"
fi
echo " remove temp folder $TempDir"
rm -rf $TempDir
echo ""
echo -n "Hit Any Key:"
read -r -n 1 -s answer
echo ""

